[package]
name = "multicid"
version = "1.1.0"
edition = "2021"
authors = ["Dave Grantham <dwg@linuxprogrammer.org>"]
description = "Multicodec compatible content identifier implementation"
repository = "https://github.com/cryptidtech/multicid.git"
readme = "README.md"
license = "Apache-2.0"

[features]
default = ["serde"]
dag_cbor = ["serde_cbor", "serde_cbor/tags"]

[dependencies]
multibase = { version = "1.0", git = "https://github.com/cryptidtech/rust-multibase.git" }
multicodec = { version = "1.0", git = "https://github.com/cryptidtech/rust-multicodec.git" }
multihash = { version = "1.0", git = "https://github.com/cryptidtech/multihash.git" }
multikey = { version = "1.0", git = "https://github.com/DougAnderson444/multikey.git" }
multisig = { version = "1.0", git = "https://github.com/DougAnderson444/multisig.git" }
multitrait = { version = "1.0", git = "https://github.com/cryptidtech/multitrait.git" }
multiutil = { version = "1.0", git = "https://github.com/cryptidtech/multiutil.git" }
rand = "0.8"
serde = { version = "1.0", default-features = false, features = [
  "alloc",
  "derive",
], optional = true }
serde_cbor = { version = "0.11", optional = true }
thiserror = "1.0"

[dev-dependencies]
hex = "0.4"
serde_cbor = "0.11"
serde_json = "1.0"
serde_test = "1.0"
